### ISSUE TITLE
Any other alternative to build carl in Windows along with flex dependency?

### ISSUE THREAD

**Issue by visraj1** [melgi/carl#5]
Receiving ´make errors´, while trying to build carl as well as cturtle with resepct to flexLexer.h header. But solving this results in C syntax error. Any updates on the version of flex to be used  for Windows 10?

**Comment by melgi** [comment]
A Windows binary is provided for the latest release. Can you try if it works for you?

**Comment by visraj1** [comment]
Thanks. Its working now.
