### ISSUE TITLE
@forAll

### ISSUE THREAD

**Issue by cristianvasquez** [melgi/carl#6]
Hello, thanks for carl.

question: how can I parse @forAll ?
I'm doing something wrong? can I workaround it?

thermostat.n3
```
@prefix : <#>.
@forAll :x.
{ :thermostat :temp :x } log:implies { :cooling :power :x } .
```

flag('no-skolem', 'https://melgi.github.io/.well-known/genid/#').
translating file:///home/crvasque/thermostat.n3
scope('<file:///home/crvasque/thermostat.n3>').
pfx(':','<file:///home/crvasque/thermostat.n3#>').
parse error at line 2: expected base, prefix or triple

**Comment by melgi** [comment]
Because the scope of explicitly declared variables with `@forAll` is unclear, carl currently does not support them.
You can however use implicit universal variables:
```
@prefix : <#>. 

{ :thermostat :temp ?x } => { :cooling :power ?x } .
```

**Comment by cristianvasquez** [comment]
Thanks very much!
